#!/usr/bin/env python
targets = [
    Target('HaskellSwift'),
    Target('PackageDescription'),

    # Test targets.
    Target('data-tests', subpath="../Tests/data",
        dependencies=["HaskellSwift"],
        is_test=True),
    Target('control-tests', subpath="../Tests/control",
        dependencies=["HaskellSwift"],
        is_test=True)
    ]
