#!/usr/bin/env python
targets = [
    Target('HaskellSwift'),
    Target('PackageDescription'),
    #Target('Data'),
    #Target('POSIX', dependencies=["libc"]),
    #Target('sys', dependencies=["POSIX", "libc"]),
    #Target('dep', dependencies=["sys", "PackageDescription", "libc", "POSIX", "CommandLine"]),
    # Target('swift-build', dependencies=["dep", "sys", "PackageDescription",
                                        # "POSIX", "libc"]),
    # Test targets.
    # Target('PackageDescription-tests', subpath="../Tests/PackageDescription",
           # dependencies=["dep", "sys", "PackageDescription", "POSIX", "libc"],
           # is_test=True),
    # Target('sys-tests', subpath="../Tests/sys",
            # dependencies=["sys", "POSIX", "libc"],
            # is_test=True),
    Target('datalist-tests', subpath="../Tests/datalist",
        dependencies=["HaskellSwift"],
        is_test=True)
    ]
